import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import Slimbar from "@/components/slimbar/slimbar";
import SideBar from "@/components/sidebar/sidebar";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
            <header>
                <Navbar/>
                <Slimbar/>
            </header>
            <Suspense fallback={<div>laoding</div>}>
                {children}
            </Suspense>
            <Footer/>
        </body>
    </html>
  );
}
